// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://queyvbvjmwxyrotzbxcr.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InF1ZXl2YnZqbXd4eXJvdHpieGNyIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ1MDAwNjUsImV4cCI6MjA2MDA3NjA2NX0.6o7XP-cXCkvLDaTOE9Uo9cCbsRvcqwQgj6smZtTOCfg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);